// contivModel.js
// This file is auto generated by modelgen tool
// Do not edit this file manually

var networkSummaryView = React.createClass({
	// Walk thru all objects
	var networkListView = self.props.policies.map(function(network){
		return (
			<tr key={ network.key } className="info">
			
			 
				<td>{ network.encap }</td>     
				<td>{ network.networkName }</td>  
				<td>{ network.pktTag }</td>  
				<td>{ network.subnet }</td>  
				<td>{ network.tenantName }</td> 
			</tr>
		);
	});

  	render: function() {
		return (
        <div>
			<Table hover>
				<thead>
					<tr>
					
					 
						<td> Network Name </td>     
						<td> Network Name </td>  
						<td> Network Name </td>  
						<td> Network Name </td>  
						<td> Network Name </td> 
					</tr>
				</thead>
				<tbody>
            		{ networkListView }
				</tbody>
			</Table>
        </div>
    	);
	}
});

var networkModalView = React.createClass({
	render() {
		var obj = this.props.network
	    return (
	      <Modal {...this.props} bsStyle='primary' bsSize='large' title='New network' animation={false}>
	        <div className='modal-body' style={ {margin: '5%',} }>
			
			
				<Input type='text' label='Network Name' ref='encap' defaultValue={obj.encap} placeholder='Network Name' />
			
				<Input type='text' label='Network Name' ref='isPrivate' defaultValue={obj.isPrivate} placeholder='Network Name' />
			
				<Input type='text' label='Network Name' ref='isPublic' defaultValue={obj.isPublic} placeholder='Network Name' />
			
				<Input type='text' label='Network Name' ref='labels' defaultValue={obj.labels} placeholder='Network Name' />
			
				<Input type='text' label='Network Name' ref='networkName' defaultValue={obj.networkName} placeholder='Network Name' />
			
				<Input type='text' label='Network Name' ref='pktTag' defaultValue={obj.pktTag} placeholder='Network Name' />
			
				<Input type='text' label='Network Name' ref='subnet' defaultValue={obj.subnet} placeholder='Network Name' />
			
				<Input type='text' label='Network Name' ref='tenantName' defaultValue={obj.tenantName} placeholder='Network Name' />
			
			</div>
	        <div className='modal-footer'>
				<Button onClick={this.props.onRequestHide}>Close</Button>
	        </div>
	      </Modal>
	    );
  	}
});

module.exports.networkSummaryView = networkSummaryView
module.exports.networkModalView = networkModalView
	
var tenantSummaryView = React.createClass({
	// Walk thru all objects
	var tenantListView = self.props.policies.map(function(tenant){
		return (
			<tr key={ tenant.key } className="info">
			
			 
			</tr>
		);
	});

  	render: function() {
		return (
        <div>
			<Table hover>
				<thead>
					<tr>
					
					 
					</tr>
				</thead>
				<tbody>
            		{ tenantListView }
				</tbody>
			</Table>
        </div>
    	);
	}
});

var tenantModalView = React.createClass({
	render() {
		var obj = this.props.tenant
	    return (
	      <Modal {...this.props} bsStyle='primary' bsSize='large' title='New tenant' animation={false}>
	        <div className='modal-body' style={ {margin: '5%',} }>
			
			
				<Input type='text' label='' ref='tenantName' defaultValue={obj.tenantName} placeholder='' />
			
			</div>
	        <div className='modal-footer'>
				<Button onClick={this.props.onRequestHide}>Close</Button>
	        </div>
	      </Modal>
	    );
  	}
});

module.exports.tenantSummaryView = tenantSummaryView
module.exports.tenantModalView = tenantModalView
	