/***
Copyright 2014 Cisco Systems Inc. All rights reserved.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at
http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

package main

import (
	"bytes"

	"text/template"

	"github.com/contiv/objmodel/tools/modelgen/generators"
	"github.com/contiv/objmodel/tools/modelgen/texthelpers"
)

var funcMap = template.FuncMap{
	"initialCap":    texthelpers.InitialCap,
	"initialLow":    texthelpers.InitialLow,
	"depunct":       texthelpers.Depunct,
	"capFirst":      texthelpers.CapFirst,
	"translateType": texthelpers.TranslatePropertyType,
}

func (s *Schema) GenerateJs() (string, error) {
	var goStr string
	var buf bytes.Buffer

	const hdr = `// {{.}}.js
// This file is auto generated by modelgen tool
// Do not edit this file manually
`

	// Generate file headers
	tmpl, _ := template.New("hdrTmpl").Funcs(funcMap).Parse(hdr)
	tmpl.Execute(&buf, s.Name)
	goStr = goStr + buf.String()

	//  Generate all object Views
	for _, obj := range s.Objects {
		objStr, err := obj.GenerateJsViews()
		if err == nil {
			goStr = goStr + objStr
		}
	}

	return goStr, nil
}

func (obj *Object) GenerateJsViews() (string, error) {
	goStr, err := generators.RunTemplate("jsView", obj)
	if err != nil {
		return "", err
	}

	return goStr, nil
}
